# Generated by Django 2.1.7 on 2019-03-14 09:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='MeasureCode')),
                ('value', models.FloatField(verbose_name='Value')),
                ('date', models.DateField(verbose_name='Date')),
                ('hour', models.CharField(max_length=25, verbose_name='Hour')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ParameterCode')),
                ('name', models.CharField(max_length=25, verbose_name='ParameterName')),
                ('unity_measure', models.CharField(max_length=10, verbose_name='UnityMeasure')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='measure',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measures.Parameter'),
        ),
    ]
