# Generated by Django 2.1.7 on 2019-03-14 09:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='MedicineCode')),
                ('name', models.CharField(max_length=50, verbose_name='MedicineName')),
                ('quantity', models.PositiveIntegerField(verbose_name='MedicineQuantity')),
                ('unity', models.CharField(max_length=5)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Posology',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='PosologyCode')),
                ('day_of_the_week', models.CharField(max_length=25, verbose_name='DayOfTheWeek')),
                ('hour', models.CharField(max_length=25, verbose_name='Hour')),
                ('quantity', models.CharField(max_length=25, verbose_name='Quantity')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.Medicine')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='posology',
            unique_together={('medicine', 'day_of_the_week', 'hour')},
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('patient', 'name', 'quantity', 'unity')},
        ),
    ]
